In [1]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array; 다차원배열)

In [2]:
# 리스트를 다차원배열로 변환
# array() : 다차원배열을 만드는 함수
li = [1, 2, 3, 4]
li_arr = np.array(li)

In [3]:
li_arr

array([1, 2, 3, 4])

In [4]:
type(li_arr)

numpy.ndarray

In [5]:
# 튜플을 다차원배열로 변환
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [6]:
type(tu_arr)

numpy.ndarray

In [7]:
# 배열도 mutable의 특징을 가짐
# 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨
co_arr = li_arr
id(co_arr), id(li_arr)

(2286044403568, 2286044403568)

In [8]:
co_arr[0] = 100
co_arr

array([100,   2,   3,   4])

In [9]:
li_arr

array([100,   2,   3,   4])

In [10]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열을 만들기 때문에 서로 다른 데이터가 됨
new_arr = np.array(li_arr)

In [11]:
id(new_arr), id(li_arr)

(2286039366128, 2286044403568)

In [13]:
new_arr[0] = 99
new_arr

array([99,  2,  3,  4])

In [14]:
li_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

In [15]:
# float 자료형을 지정해서 다차원 배열 만들기
fl_arr = np.array(li, dtype = float)
fl_arr

array([1., 2., 3., 4.])

In [16]:
fl_arr.dtype

dtype('float64')

## 2차원 배열

- 2개의 축을 가지는 배열(행, 열)
    - 두 개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [18]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

In [20]:
# 축이 개수
arr2d.ndim

2

In [21]:
arr2d.dtype

dtype('int32')

In [22]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

## 원소 조회하기

In [23]:
# 1차원 배열에서 원소 조회
li_arr

array([100,   2,   3,   4])

In [24]:
li

[1, 2, 3, 4]

In [25]:
li_arr[0]

100

In [26]:
li[0]

1

In [27]:
# 다차원 배열에서 원소 조회
list2d = arr2d.tolist() # 배열을 리스트로 변환

In [28]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [29]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱스를 두 번 사용해야함
list2d[0][1]

2

In [32]:
list2d[0, 1] # 에러 남

TypeError: list indices must be integers or slices, not tuple

In [33]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

2

In [34]:
arr2d[0][1]

2

### 슬라이싱


In [35]:
arr1 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
# 첫 번째 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [37]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [38]:
# 두 번째 행의 두 번째 열부터 끝 열까지
arr1[1, 1:]

array([5, 6, 7])

In [39]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

#### 연습문제

1. 아래의 행렬에서 값 7을 인덱싱
2. 아래의 행렬에서 값 14를 인덱싱
3. 아래의 행렬에서 배열 [6,7]을 슬라이싱
4. 아래의 행렬에서 배열 [7, 12]를 슬라이싱
5. 아래의 행렬에서 배열 [[3, 4], [8, 9]]를 슬라이싱

In [40]:
m = np.array([[0, 1, 2, 3, 4],
             [5, 6, 7, 8, 9],
             [10, 11, 12, 13, 14]])

In [41]:
m[1, 2]

7

In [42]:
m[2, -1]

14

In [44]:
m[1, 1:3]

array([6, 7])

In [45]:
m[1:, 2]

array([ 7, 12])

In [47]:
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [52]:
m = np.array([[[1, 2, 3], [4, 5, 6]],
             [[7, 8, 9], [10, 11, 12]],
             [[13, 14, 15], [16, 17, 18]],
             [[19, 20, 21], [22, 23, 24]]])

In [90]:
m.shape

(4, 2, 3)

In [123]:
# [8, 14]
m[1:3, 0, 1]

array([ 8, 14])

In [124]:
# [[11, 12], [17, 18]]
m[1:3, 1:, 1:]

array([[[11, 12]],

       [[17, 18]]])

In [125]:
# [3, 9, 15, 21]
m[:, 0, 2]

array([ 3,  9, 15, 21])

## 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능
- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
    - 파이썬 리스트 : 곱셈으로 리스트 요소를 반복하는 것은 가능
    
- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
    - 넘파이 배열은 수치 계싼이 많고 복잡하거나 다차원배열이 필요할 때 사용

# 전치 연산(Transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [126]:
arr = np.array([[1, 2, 3,], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
arr.shape

(2, 3)

In [128]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [129]:
arr.T.shape

(3, 2)

# 배열 크기 변형

In [2]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr2 = arr1.reshape(3, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
arr1.reshape(3, 3) # 12개가 안 맞기 때문에 에러 뜸~

ValueError: cannot reshape array of size 12 into shape (3,3)

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소 중 하나는 -1로 대체할 수 있음

In [6]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [9]:
arr1.reshape(-1, 5)

ValueError: cannot reshape array of size 12 into shape (5)

# 넘파이 함수의 특징
 
- 벡터화 연산
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연신이라고 함
    
- 유니버설 함수(universal function)
    - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [10]:
# 일반 파이썬 함수의 타입 확인
def test():
    pass

In [11]:
type(test)

function

In [12]:
# 유니버셜 함수 확인
type(np.add)

numpy.ufunc

In [13]:
# 넘파이 모듈에는 유니버설 함수도 있고 일반 함수도 있음
type(np.sort)

function

In [14]:
list2d = [[1, 2, 3], [4, 5, 6]]

In [15]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [16]:
np.add(list2d, list2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산

### 벡터화 연산이 필요한 이유

- data 리스트 내의 각 값에 2를 곱해야 하는 경우

In [17]:
# 리스트를 통한 풀이
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
ans = []

for i in data:
    ans.append(i * 2)
    
ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [22]:
# 넘파이를 통한 풀이
data = np.array(data)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [25]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [26]:
2 * a + b

array([12, 24, 36])

In [27]:
a == 2 # 하나 하나 요소들에 비교

array([False,  True, False])

In [28]:
[1, 2, 3] == 2

False

In [29]:
b > 10

array([False,  True,  True])

In [30]:
(a == 2) &  (b > 10)

array([False,  True, False])

In [31]:
a[[True, False, True]]

array([1, 3])

In [32]:
a[[False, False, True]]

array([3])

In [33]:
a[a == 2]

array([2])

- 배열끼리의 연산

In [35]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [37]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [38]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셈한 결과인 1차원 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [40]:
# arr1에 차원 추가(수직축 추가)
new_arr1 = arr1.reshape(-1, 1)
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [41]:
# arr2에 차원 추가(수평축 추가)
new_arr2 = arr2.reshape(1, -1)
new_arr2

array([[10, 11, 12, 13]])

In [42]:
new_arr2.shape

(1, 4)

## 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야 함
- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤


In [43]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

In [44]:
# 행렬곱 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [45]:
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [46]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [47]:
a

array([[1, 2],
       [3, 4]])

In [48]:
b

array([[5, 6],
       [7, 8]])

In [49]:
# * 연산자는 요소별 곱셈을 수행
a * b

array([[ 5, 12],
       [21, 32]])

In [50]:
# @ 연산자는 행렬 곱셈을 수행
a @ b

array([[19, 22],
       [43, 50]])

#### 연습문제

1. 아래의 배열에서 3의 배수를 찾기
2. 아래의 배열에서 4로 나누면 1이 남는 수 찾기
3. 아래의 배열에서 3으로 나누어지고 4로 나누면 1이 남는 수 찾기

In [51]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [61]:
x[2::3]

array([ 3,  6,  9, 12, 15, 18])

In [58]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [60]:
#  3으로 나누어지고 4로 나누면 1이 남는 수 
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## 축에 따른 연산

- 동일한 축에 있는 원소들을 계산하기 위해서 필요

In [62]:
# 1차원 배열
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [63]:
# 합계
np.sum(arr1)

10

In [64]:
arr1.sum()

10

In [65]:
# 최댓값
arr1.max()

4

In [66]:
# 최솟값
arr1.min()

1

In [67]:
# 최솟값의 위치
arr1.argmin()

0

In [68]:
arr1.argmax()

3

In [69]:
# 평균
arr1.mean()

2.5

In [70]:
# 중앙값
np.median(arr1)

2.5

In [71]:
# 2차원 배열
arr2 = arr1.reshape(2, 2)
arr2

array([[1, 2],
       [3, 4]])

In [72]:
# 모든 원소를 더한 합
np.sum(arr2)


10

In [73]:
# 수직방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [74]:
# 수평방향으로 같은 행에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [75]:
# 3차원 배열
arr3 = np.arange(1, 9)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
arr4 = arr3.reshape(2, 2, 2)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [77]:
# 모든 원소를 더한 합
np.sum(arr4)

36

In [78]:
# 두 개의 행렬의 동일한 인덱스의 원소를 합한 값
np.sum(arr4, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [79]:
# 각 2차원 배열의 0번축(열)의 합
np.sum(arr4, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [80]:
# 각 2차원 배열의 1번축(행)의 합
np.sum(arr4, axis = 2)

array([[ 3,  7],
       [11, 15]])

#### 연습문제

1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [83]:
x = np.random.random((5, 6))
x

array([[0.28733508, 0.11470513, 0.67269485, 0.70625154, 0.68984142,
        0.24184574],
       [0.37181315, 0.15727288, 0.24552989, 0.48989981, 0.11569317,
        0.92160271],
       [0.19786255, 0.2728979 , 0.2476661 , 0.85615561, 0.5257666 ,
        0.74322289],
       [0.23663734, 0.33334422, 0.29158338, 0.55991459, 0.65004315,
        0.28762448],
       [0.85887411, 0.44371063, 0.6024273 , 0.85083017, 0.7340549 ,
        0.14342822]])

In [84]:
x.max()

0.9216027066421129

In [86]:
x.shape # 행, 열

(5, 6)

In [95]:
x.sum(axis = 1) 

array([2.71267376, 2.3018116 , 2.84357166, 2.35914716, 3.63332532])

In [96]:
x.max(axis = 1)

array([0.70625154, 0.92160271, 0.85615561, 0.65004315, 0.85887411])

In [99]:
x.mean(axis = 0)

array([0.39050445, 0.26438615, 0.4119803 , 0.69261034, 0.54307985,
       0.46754481])

In [98]:
x.min(axis = 0)

array([0.19786255, 0.11470513, 0.24552989, 0.48989981, 0.11569317,
       0.14342822])

In [100]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [101]:
arr4.sum(axis = 0)

array([[ 6,  8],
       [10, 12]])

In [102]:
arr4.sum(axis = 1)

array([[ 4,  6],
       [12, 14]])

In [103]:
arr4.sum(axis = 2)

array([[ 3,  7],
       [11, 15]])

In [104]:
arr4.sum(axis = (0,1))

array([16, 20])

In [105]:
arr4.sum(axis = (0,2))

array([14, 22])

In [106]:
arr4.sum(axis = (1,2))

array([10, 26])

In [107]:
arr5 = np.random.randint(0, 3, (2, 3, 4))
arr5

array([[[0, 0, 0, 2],
        [0, 1, 2, 0],
        [1, 0, 1, 2]],

       [[0, 0, 1, 2],
        [2, 1, 1, 1],
        [1, 2, 0, 0]]])

In [108]:
arr5.sum(axis = 0)

array([[0, 0, 1, 4],
       [2, 2, 3, 1],
       [2, 2, 1, 2]])

In [109]:
arr5.sum(axis = 1)

array([[1, 1, 3, 4],
       [3, 3, 2, 3]])

In [110]:
arr5.mean(axis = 2)

array([[0.5 , 0.75, 1.  ],
       [0.75, 1.25, 0.75]])

In [111]:
arr5.sum(axis = 2)

array([[2, 3, 4],
       [3, 5, 3]])

In [113]:
arr5.mean(axis = (0, 1))

array([0.66666667, 0.66666667, 0.83333333, 1.16666667])

In [114]:
arr5.mean(axis = (0, 2))

array([0.625, 1.   , 0.875])

In [115]:
arr5.mean(axis = (1, 2))

array([0.75      , 0.91666667])

In [116]:
data_3d = np.random.random((3, 5, 6))
data_3d

array([[[0.10585683, 0.23202264, 0.33002006, 0.27042762, 0.30657382,
         0.1141149 ],
        [0.44924896, 0.2759078 , 0.43782547, 0.32604656, 0.13511846,
         0.44572353],
        [0.5436644 , 0.88050025, 0.95857394, 0.32875011, 0.03040773,
         0.88490107],
        [0.91311479, 0.81466932, 0.66413126, 0.64632077, 0.32537446,
         0.55167124],
        [0.07853278, 0.09237694, 0.25397397, 0.63222071, 0.30272846,
         0.45919196]],

       [[0.2271191 , 0.88798076, 0.0099221 , 0.61351314, 0.60192938,
         0.1942378 ],
        [0.86120446, 0.92620349, 0.19555722, 0.22569114, 0.32343056,
         0.38893802],
        [0.60562377, 0.61301056, 0.64817838, 0.01401209, 0.22639111,
         0.59795467],
        [0.28930282, 0.68885908, 0.48984478, 0.09662318, 0.88312991,
         0.46968105],
        [0.4549279 , 0.39500015, 0.20495961, 0.33417669, 0.43844304,
         0.2089517 ]],

       [[0.66004141, 0.92482277, 0.07356783, 0.53735614, 0.84714272,
         0.204084

1. 각 2차원 배열에서의 최댓값
2. 각 2차원 배열에서의 행의 합
3. 각 2차원 배열에서의 각 행의 최댓값
4. 전체 열의 평균
5. 각 2차원 배열에서의 열의 평균
6. 각 2차원 배열에서의 각 열의 최솟값


In [117]:
data_3d.shape

(3, 5, 6)

In [146]:
data_3d.max(axis = (1, 2))

array([0.95857394, 0.92620349, 0.94832754])

In [149]:
data_3d.sum(axis = 2)

array([[1.35901586, 2.06987078, 3.62679749, 3.91528184, 1.81902483],
       [2.53470227, 2.92102489, 2.70517058, 2.91744083, 2.03645909],
       [3.24701555, 2.56548075, 3.00219583, 2.71292831, 3.3972511 ]])

In [150]:
data_3d.max(axis = 2)

array([[0.33002006, 0.44924896, 0.95857394, 0.91311479, 0.63222071],
       [0.88798076, 0.92620349, 0.64817838, 0.88312991, 0.4549279 ],
       [0.92482277, 0.94483013, 0.74740487, 0.94832754, 0.80689522]])

In [151]:
data_3d.mean(axis = (0, 1))

array([0.47393986, 0.52921512, 0.46991448, 0.42365015, 0.4462825 ,
       0.3789752 ])

In [154]:
data_3d.mean(axis = 1)

array([[0.41808355, 0.45909539, 0.52890494, 0.44075316, 0.22004058,
        0.49112054],
       [0.48763561, 0.70221081, 0.30969242, 0.25680325, 0.4946648 ,
        0.37195265],
       [0.51610043, 0.42633918, 0.57114608, 0.57339406, 0.62414213,
        0.27385243]])

In [155]:
data_3d.min(axis = 1)

array([[0.07853278, 0.09237694, 0.25397397, 0.27042762, 0.03040773,
        0.1141149 ],
       [0.2271191 , 0.39500015, 0.0099221 , 0.01401209, 0.22639111,
        0.1942378 ],
       [0.06851224, 0.01256059, 0.07356783, 0.29278914, 0.17729756,
        0.14002788]])

# Inf와 nan

- 넘파이에서는 무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan이 있음


In [156]:
1 / 0

ZeroDivisionError: division by zero

In [157]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\ITSC\AppData\Local\Temp\ipykernel_6304\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\ITSC\AppData\Local\Temp\ipykernel_6304\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])